version: "3.7"
x-sockets_dev: &node_dev
  image: node:14.5.0
  volumes:
    - node__modules:/app/code/node_modules
    - .:/app/code
  working_dir: /app/code

services:
  envoy:
    build:
      context: .
      dockerfile: envoy.front.Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
      - 9901:9901
    networks:
      - envoymesh
    volumes:
      - ./volumes/envoy/dev.envoy.yaml:/etc/envoy/envoy.yaml
      - ./volumes/envoy/logs/:/var/log/envoy/

volumes:
  node__modules:
    external: true
networks:
  envoymesh: {}
